// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "math-timer.h"

Fl_Double_Window* UserInterface::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(220, 200, "math-timer");
    w = o;
    o->user_data((void*)(this));
    o->end();
  } // Fl_Double_Window* o
  return w;
}

int main() {
  UserInterface ui;
  ui.make_window()->show();
  return Fl::run();
}
