// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef math_timer_h
#define math_timer_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
};
int main();
#endif
